spring:
  application:
    name: ProductService
  jackson:
    serialization:
      indent-output: true
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    
      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

        